---
title: "ADNI, AIBL, UK biobank Data - Descriptive Analysis"
author: "Uditi Shah"
date: '2024-08-13'
output: html_document
---

```{r}

# Install and load the tidyverse package, which is a collection of packages for data manipulation and visualization.
# install.packages("tidyverse")
library(tidyverse)

# readr: For reading CSV files
# dplyr: For data manipulation
# ggplot2:For plots and graphs
# tidyr: For tidying and reshaping data into a tidy format.
# purrr: For functional programming and working with lists and vectors.
# tibble: For creating and working with modern data frames.
# stringr: For string manipulation and text processing.
# forcats: For working with categorical data and factors.
# lubridate: For working with dates and times.
# magrittr: For creating expressive pipelines using the pipe operator %>%.
# rlang: For advanced manipulation and programming with R expressions.


# Install the 'tableone' package for quickly understanding the distribution of variables as it allows for generating summary tables and statistics (means, medians, counts, and percentages) for comparing characteristics between different treatment/demographic groups or other categorical variables in a dataset. 
# install.packages("remotes")
# remotes::install_github("kaz-yos/tableone")
library(tableone)
```

```{r}

# Use read.csv() to load a CSV file
data <- read.csv("df_comb_ml.csv")
View(data)
```

```{r}

# Display the first 5 lines
head(data, 5)
```

```{r}
# dimensions
dim(data)
# 57066 rows and 15 columns
```

```{r}
# all the possible unique values that exist for each column/variable
length(unique(data$ID))
# this means that there are 57066 individuals in our data set

# filter is for rows
# select is for columns
# this can show us if there are NA = missing data, none = or unknown = which mean diff things
# table (ColumnName)
```

```{r}
# column/variable names
names(data)

# Attached is a set of data from ADNI, AIBL and UK Biobank
# ID    - Sample.id
# AGE    - Age in years
# SEX - is female (?)
# EDU   - years of education, bit different across cohorts
# FH  - Parental history of AD
# APOE4  - # of copies of APOE4 (0,1,2)
# DX - Diagnosis (baseline?)
# dataset - AIBL/ADNI/UKB
# conv - Do they Convert to AD or not
# AGE.bl - What is their age at baseline
# event_time - When do they convert to AD or leave the study
# APOE4_e4e4 - Do they have 2 copies of APOE4?
# FH_na - Is their family history missing?
# conv_fh - Do they have a history of AD or not (FH!=0)
```

```{r}


# Install and load the naniar package, which provides functions for exploring missing data patterns.
# install.packages("naniar")
library(naniar)

# View all the rows with dataset = ADNI 
ADNI <- data[data$dataset == "ADNI", ]
length(unique(AIBL$ID))
length(unique(UKBB$ID))
# View(ADNI)

gg_miss_var(ADNI) + ggtitle("Missing Values in Each Column of ADNI Dataset")
vis_miss(ADNI) + labs(title = "Heatmap of Missing Values in ADNI Dataset")

# View all the rows with dataset = ABIL 
AIBL <- data[data$dataset == "AIBL", ]
sum(is.na(AIBL$EDU))

AIBL <- AIBL[!is.na(AIBL$EDU), ]
sum(is.na(AIBL$EDU))
# View(AIBL)

gg_miss_var(AIBL) + ggtitle("Missing Values in Each Column of AIBL Dataset")
vis_miss(AIBL) + labs(title = "Heatmap of Missing Values in AIBL Dataset")

# View all the rows with dataset = UKBiobank 
UKBB <- data[data$dataset == "UKB", ]
# Check for any rows where EDU is NA
sum(is.na(UKBB$EDU))
UKBB <- UKBB[!is.na(UKBB$EDU), ]
sum(is.na(UKBB$EDU))


names(UKBB)[names(UKBB) == "AGE"] <- "AGE.followup"

names(UKBB)[names(UKBB) == "AGE.bl"] <- "AGE"



View(UKBB)

# View all the rows with conv = 0
nonconvertors <- data[data$conv == 0, ]
# View(nonconvertors)

gg_miss_var(nonconvertors) + ggtitle("Missing Values in Each Column of nonconvertors Dataset")
vis_miss(nonconvertors) + labs(title = "Heatmap of Missing Values in nonconvertors Dataset")

# View all the rows with conv = 1
convertors <- data[data$conv == 1, ]
# View(convertors)

gg_miss_var(convertors) + ggtitle("Missing Values in Each Column of convertors Dataset")
vis_miss(convertors) + labs(title = "Heatmap of Missing Values in convertors Dataset")

# prune the datasets to only have the columns we want in our table01
UKBB <- UKBB %>% select(-FH_na, -conv_fh, -APOE4_e4e4)
AIBL <- AIBL %>% select(-FH_na, -conv_fh, -APOE4_e4e4)
ADNI <- ADNI %>% select(-FH_na, -conv_fh, -APOE4_e4e4)
View(UKBB)
```

# Save preprocessed data to a CSV file

```{r}

write.csv(ADNI, "ADNI_subset.csv", row.names=FALSE)
write.csv(AIBL, "AIBL_subset.csv", row.names=FALSE)
write.csv(UKBB, "UKBB_subset.csv", row.names=FALSE)
```

### Table 01 for UKBB

\# prune the datasets to only have the columns we want in our table01

```{r}


count_tablev7 <- ADNI %>%
  group_by(conv) %>%
  summarise(Count = n())
# View(count_tablev7)
sum(count_tablev7$Count)

count_tablev8 <- UKBB %>%
  group_by(conv) %>%
  summarise(Count = n())
# View(count_tablev8)
sum(count_tablev8$Count)

count_tablev9 <- AIBL %>%
  group_by(conv) %>%
  summarise(Count = n())
# View(count_tablev9)
sum(count_tablev9$Count)


## TABLE 01
# Create a variable list which we want in Table 1
listVars <- c("AGE.bl", "EDU", "SEX", "APOE4", "FH")
 
# Define categorical variables
# catVars <- c("DX","PTGENDER")
catVars <- c("SEX")

table1_UKBB <- CreateTableOne(vars = listVars, data = UKBB, factorVars = catVars, strata = c("conv"))
print(table1_UKBB)

```

### Table 01 for ABIL

```{r}

## TABLE 01
# Create a variable list which we want in Table 1
listVars <- c("AGE.bl", "EDU", "SEX", "APOE4", "FH")
 
# Define categorical variables
# catVars <- c("DX","PTGENDER")
catVars <- c("SEX")

table1_AIBL <- CreateTableOne(vars = listVars, data = AIBL, factorVars = catVars, strata = c("conv"))
print(table1_AIBL)
```

### Table 01 for ADNI

```{r}

## TABLE 01
# Create a variable list which we want in Table 1
listVars <- c("AGE.bl", "EDU", "SEX", "APOE4", "FH")
 
# Define categorical variables
# catVars <- c("DX","PTGENDER")
catVars <- c("SEX")

table1_ADNI <- CreateTableOne(vars = listVars, data = ADNI, factorVars = catVars, strata = c("conv"))
print(table1_ADNI)
```

## Regression analysis using the SNP FILE

1.  Install relevant packages:

```{r}

install.packages("pbapply")
library(pbapply)

install.packages("ggplot2")
library(ggplot2)

install.packages("GGally")
library(GGally)
```

2.  Load the Dataset

```{r}
geno_covar <- readRDS("ukb_adni_genotypes_58_snps_v2.RDS")
# View(geno_covar)


print(geno_covar[geno_covar$FID == 1000015, ])

# column/variable names
names(geno_covar)

print(data[data$ID == 1000015, ])

```

3.  Binary Classification - Demographics - XGBoost Model Predictions
